Repository google/mobly-snippet-lib, pull requests merged in 2023-05, with the labels that each got.

#124 Fix Java style, lint, and best practices warning.
  third_party/sl4a/src/main/java/com/google/android/mobly/snippet/rpc/MethodDescriptor.java
  third_party/sl4a/src/main/java/com/google/android/mobly/snippet/rpc/RpcError.java
Labels: improvement

#118 Update README.md
  examples/ex1_standalone_app/README.md
Labels: bug

#126 Deprecate non-primitive array types and enable checked warnings in Js…
  third_party/sl4a/src/main/java/com/google/android/mobly/snippet/rpc/JsonBuilder.java
  third_party/sl4a/src/main/java/com/google/android/mobly/snippet/rpc/MethodDescriptor.java
  third_party/sl4a/src/main/java/com/google/android/mobly/snippet/util/AndroidUtil.java
Labels: improvement

#127 Snippet lib release v1.4.0
  CHANGELOG
  examples/ex1_standalone_app/README.md
  examples/ex1_standalone_app/build.gradle
  examples/ex2_espresso/README.md
  examples/ex2_espresso/build.gradle
  examples/ex3_async_event/build.gradle
  examples/ex4_uiautomator/build.gradle
  examples/ex5_schedule_rpc/build.gradle
  examples/ex6_complex_type_conversion/build.gradle
  examples/ex7_default_and_optional_rpc/build.gradle
  third_party/sl4a/gradle.properties
Labels: toolchain
